services:
  database:
    image: postgres:17
    container_name: botikkk2004_database
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      - database.env
    ports:
      - "127.0.0.1:5432:5432"