"""Create botikkk2004_users table

Revision ID: 695c9d4585c9
Revises: 72698a74d4ea
Create Date: 2025-09-20 03:07:53.252924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695c9d4585c9'
down_revision: Union[str, Sequence[str], None] = '72698a74d4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('botikkk2004_users', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        # ### end Alembic commands ###

def downgrade() -> None:
    with op.batch_alter_table('botikkk2004_users', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=False)
        # ### end Alembic commands ###