"""Added users table

Revision ID: 72698a74d4ea
Revises: 
Create Date: 2025-09-20 02:46:46.081686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72698a74d4ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botikkk2004_users',
                    sa.Column('telegram_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=True),
                    sa.Column('first_name', sa.String(length=50), nullable=False),
                    sa.Column('last_name', sa.String(length=50), nullable=True),
                    sa.Column('phone', sa.String(length=20), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('registered_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('telegram_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('botikkk2004_users')
    # ### end Alembic commands ###